### ISSUE TITLE
nginx 502:Bad Gateway issue

### ISSUE THREAD

**Issue by slarionoff** [jed-frey/FreeNAS-Gitea#10]
Hi there!
I install gitea on my FreeNAS using you manual. It looks OK, thank you for that! 
On the last step, setup, in Chrome I see an error "NET::ERR_CERT_AUTHORITY_INVALID" (In FireFox an error is similar). After passing it by I see In nginx log I can see this:

2019/03/19 17:59:51 [crit] 17346#100781: *37 connect() to unix:/tmp/gitea.sock failed (2: No such file or directory) while connecting to upstream, client: <client IP>, server: _, request: "GET /user/sign_up/ HTTP/1.1", upstream: "http://unix:/tmp/gitea.sock:/user/sign_up/", host: "<server IP>"
2019/03/19 17:59:51 [crit] 17346#100781: *37 connect() to unix:/tmp/gitea.sock failed (2: No such file or directory) while connecting to upstream, client: <client IP>, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/tmp/gitea.sock:/favicon.ico", host: "<server IP>", referrer: "https://<server IP>/user/sign_up/"

Could you please tell what I did wrong? Thank you!
I tried to create a file /tmp/gitea.sock, but looks like it is improper way as I got different message, like, "use file instead of the socket", so I just dropped it.

**Comment by slarionoff** [comment]
I've created a socket using the following command:
python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/tmp/gitea.sock')"

but now it says "connect() to unix:/tmp/gitea.sock failed (13: Permission denied)". 

ls -a /tmp gives me
srwxr-xr-x  1 root   wheel  0 Mar 19 18:34 gitea.sock

**Comment by jed-frey** [comment]
Is gitea running?

**Comment by slarionoff** [comment]
Hi Jed-frey! Looks like the answer is yes:
# service -e
/etc/rc.d/cleanvar
/etc/rc.d/newsyslog
/etc/rc.d/syslogd
/etc/rc.d/virecover
/etc/rc.d/motd
/usr/local/etc/rc.d/redis
/usr/local/etc/rc.d/nginx
/usr/local/etc/rc.d/mysql-server
/usr/local/etc/rc.d/gitea
/etc/rc.d/sshd
/etc/rc.d/cron

**Comment by jed-frey** [comment]
```
     -e  List services that are enabled.  The list of scripts to check is
         compiled using rcorder(8) the same way that it is done in rc(8), then
         that list of scripts is checked for an "rcvar" assignment.  If
         present the script is checked to see if it is enabled.
```

Is it running?

**Comment by slarionoff** [comment]
Thank you for clarification. I ran the following command and it returned nothing:
ps -awx -l | grep gitea

I see in /usr/local/etc/rc.d/gitea that 
: ${gitea_user:="git"}
but when I run jexec command, I am logged under root. Can it be the reason that this service is not started?

**Comment by jed-frey** [comment]
Have you tried to start gitea? ```service start gitea```.

If so, what does the log say?

**Comment by slarionoff** [comment]
Hi Jed-frey! In /var/log/gitea/gitea.log I saw:
2019/03/28 17:50:39 [....io/gitea/cmd/web.go:159 runWeb()] [E] Failed to remove unix socket directory /tmp/gitea.sock: remove /tmp/gitea.sock: operation not permitted

I remember that I've created this file manually myself, so I removed it and restart service. After that a page is shown properly, so an issue can be closed. 

Thank you for support!
